:toc:
:icons: font
= Kotlin Twitch Chat Client for Spring Boot

A purely Kotlin library, providing integration of https://dev.twitch.tv/docs/irc/guide#Twitch_IRC_Capabilities[Twitch IRC capabilities] within JVM based applications (mainly intended for use with Spring Boot) by leveraging https://docs.spring.io/spring-integration/reference/html/web-sockets.html[Spring's WebSocket Support].

== Artifacts

=== Repositories

The project artifacts are currently only available through https://github.com/sykq?tab=packages&repo_name=twitch-chat-client[GitHub Packages].

To use them within your own project, see the corresponding documentation https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#installing-a-package[Installing a Gradle package].

=== Core

To use this library add the following dependency to the gradle build file:

[source,groovy]
.build.gradle
----
dependencies {
    implementation "io.github.sykq:twitch-chat-client-core:0.0.1"
}
----

[source,kotlin]
.build.gradle.kts
----
dependencies {
    implementation("io.github.sykq:twitch-chat-client-core:0.0.1")
}
----

When using maven, add the following to the `dependencies` sections of your `pom.xml``:

[,xml]
.pom.xml
----
<dependency>
    <groupId>io.github.sykq</groupId>
    <artifactId>twitch-chat-client-core</artifactId>
    <version>0.0.1</version>
</dependency>
----

=== Spring Boot

To use this library in a Spring Boot application, add the following Spring Boot Starter to the dependency section of your gradle build file:

[source,groovy]
.build.gradle
----
dependencies {
    implementation "io.github.sykq:twitch-chat-client-spring-boot-starter:0.0.1"
}
----

[source,kotlin]
.build.gradle.kts
----
dependencies {
    implementation("io.github.sykq:twitch-chat-client-spring-boot-starter:0.0.1")
}
----

When using maven, add the following to the `dependencies` sections of your `pom.xml``:

[,xml]
.pom.xml
----
<dependency>
    <groupId>io.github.sykq</groupId>
    <artifactId>twitch-chat-client-spring-boot-starter</artifactId>
    <version>0.0.1</version>
</dependency>
----

== Usage

[TIP]
====
This project's API uses Kotlin's https://kotlinlang.org/docs/lambdas.html#function-literals-with-receiver[function literals with receiver] feature in several places.

Make sure you're familiar with it to effectively use this library.
====

=== TmiClient

The `io.github.sykq.tcc.TmiClient` class is part of the core library and facilitates the connection with the Twitch Messaging Interface.

To create a new TmiClient instance use the `tmiClient()` factory method within the `io.github.sykq.tcc` package:

[source,kotlin]
----
import io.github.sykq.tcc.tmiClient

fun main() {
    val tmiClient = tmiClient {
        // configure your instance
        username = "myTwitchChatBot"
        passwordProperty = "TMI_CLIENT_PASSWORD" <1>

        // define the channels to join
        channels += "myChannel"
        channels += "someOtherChannel"

        onConnect {
            join("yetAnotherChannel") <2>
            textMessage("connected") <3>
        }
    }

    tmiClient.block { message ->
        // specify what should happen upon receiving a message
        if (message.text == "!hello") {
            textMessage("Hi ${message.user}")
        }
    }
}
----
<1> the passwordProperty can be set to the name of an environment variable of system property whose value will be used as the password for connecting to the TMI
<2> optionally join another channel upon connecting
<3> set an optional `onConnect` action, which will send the text "connected" to all joined channels

To connect to the Twitch Messaging Interface (TMI) through the `TmiClient` you need to provide your Twitch username (login name) in lowercase as the `username` and an associated OAuth token as the `password`.
Such a token can be generated with the help of the https://twitchapps.com/tmi/[Twitch Chat Password Generator].

[TIP]
====
Instead of directly setting the password through the `password` property, the `TmiClient` supports reading an according value from an environment variable or system property with the name of the given by the `passwordProperty`.

By default, the environment variable/system property with key *TMI_CLIENT_PASSWORD* is used to retrieve the password.

The same functionality is present for the `usernameProperty` to read the username from an environment variable or system property.
Here, the key *TMI_CLIENT_USERNAME* is used as the default key.

These properties are only read if no password or username are explicitly set within the TmiClient's configurer during initialization.
====

See https://dev.twitch.tv/docs/irc/guide#connecting-to-twitch-irc[Connecting to Twitch IRC] in the official docs for details on how to use your Twitch account to connect to the TMI.

=== With Spring Boot

Adding the spring-boot-starter listed in <<Spring Boot>> to your Spring Boot project will pull in a AutoConfiguration which adds a `BotRegistry`-Bean to the ApplicationContext and provide the additional `BotBase`, `Bot` and `ReactiveBot` interfaces which serve as an additional layer above the TmiClient, allowing for implementations to hold bot-specific state.

== Features

=== TmiClient

==== Automatic `PONG`

The TMI-Server will send a `PING` message once about every five minutes.
To ensure that the connection is not terminated, the TmiClient will automatically reply to all such messages with a `PONG`.

==== Sink for messages from sources independent of incoming messages

The TmiClient's `messageSink` allows for writing of text messages to joined channels, which aren't created as a response to an incoming message, but rather come from an independent source (e.g. some user interaction).

Therefore, it should be possible to implement an interactive chat client on top of a TmiClient.

[source,kotlin]
.Example for a TmiClient with a message sink
----
import reactor.core.publisher.Sinks

fun main() {
    val sink = Sinks.many().unicast().onBackpressureBuffer<String>() <1>
    sink.tryEmitNext("hello")
    sink.tryEmitNext("hello again")

    val tmiClient = tmiClient {
        // configure your instance
        username = "myUsername"
        passwordProperty = TmiClient.TMI_CLIENT_PASSWORD_KEY

        // define the channels to join
        channels += "myChannel"

        messageSink = sink
    }

    tmiClient.block { message ->
        println(message.text)
    }

}
----
<1> `onBackpressureBuffer()` replays all emissions pushed to this sink while no subscriber is registered, to the first (and only, since `unicast()` is used) subscriber.
This allows us in this demo to push to the sink before the TmiClient establishes a connection to the TMI.

=== TmiSession

The `io.github.sykq.tcc.TmiSession` class is a wrapper over Spring's `WebSocketSession` and provides methods specifically tailored for interacting with the TMI as well as the list of currently joined channels as the member variable `joinedChannels`.

This class (and its subclass `ConfigurableTmiSession`) is part of the signature of most of ``TmiClient``'s `onConnect()` and `onMessage()` variants.

[[twitch_irc_capabilities]]
[TIP]
====
An instance of `ConfigurableTmiSession` is provided as parameter of the `onConnect()` functions used by a TmiClient.

It offers methods to activate https://dev.twitch.tv/docs/irc/membership[membership state event data], https://dev.twitch.tv/docs/irc/tags[tags] and https://dev.twitch.tv/docs/irc/commands[commands] capabilities.

E.g. to enrich incoming messages with tags, use the following instruction in an `onConnect()` function:

[source,kotlin]
----
import io.github.sykq.tcc.tmiClient

    fun main() {
        val tmiClient = tmiClient {
            // configure your instance
            // ... (omitted for brevity)
            onConnect {
                tagCapabilities() <1>
            }
        }
        // ...
    }
----
<1> activate tag capabilities
====

Instances are implicitly provided by a TmiClient when using one of the according methods to establish a connection, e.g. `connect()`, `connectAndTransform()` or `block()`.

==== Example methods

- `join()` can be used to join one or more additional channels (as in additional to the channels specified within a TmiClient's Configurer when creating a new TmiClient.
- `leave()` can be used to leave one or more channels.
- `textMessage()` can be used to send a text message to one or more channels.
The following invocation will send _Hello_ to all joined channels:
+
[source,kotlin]
----
tmiSession.textMessage("Hello")
----
+
The following will send a textMessage to all joined channels that start which name starts with the letter _a_ (this is just an artificial example which should demonstrate the possibility to reference the `joinedChannels` list):
+
[source,kotlin]
----
textMessage("Hello", *joinedChannels.filter { it.startsWith("a") }.toTypedArray())
----

- `clearChat()` sends the command `/clear` to a given channel.
Such command sending methods are available for several other command.
See the link:twitch-chat-client-core/src/main/kotlin/io/github/sykq/tcc/TmiSession.kt[TmiSession] class and its KDoc comments for the full list.

=== TmiMessage

The `io.github.sykq.tcc.TmiMessage` class represents an incoming message originating from one of the channels within the TMI.

It consists of:

- `timestamp` = the timestamp of arrival at the client.
- `channel` = the name of the originating channel of a message.
- `user` = the authoring user of a message.
- `text` = the text of a message.
- `type` = one of the supported ``TmiMessageType``s
- `tags` = the list of tags associated with a message. *NOTE:* Will only be supplied if link:#twitch_irc_capabilities[tag capabilities] are activated.

Instances are implicitly provided by a TmiClient each time `onMessage()` is invoked and one of the according methods to establish a connection, e.g. `connect()`, `connectAndTransform()` or `block()` is used.

=== OnCommandAction

=== OnCheerAction

==== CheerAmountCondition

=== Connecting with multiple accounts (Spring Boot)

TODO

=== BotRegistry (Spring Boot)

TODO

=== BotBase/Bot/ReactiveBot (Spring Boot)

TODO

== Spring Boot service sample project

A sample project consisting of a Spring Boot web service application which uses the features of this library can be found at https://github.com/sykq/twitch-chat-bot-service

== Building

[IMPORTANT]
====
Builds with JDK 16+ won't succeed since kapt uses some internal API which is no longer accessible in those builds. +
There is a solution by setting several according compiler args (--add-opens ..., see https://youtrack.jetbrains.com/issue/KT-45545#focus=Comments-27-4862682.0-0), but for now I'll stay on JDK 11 to build.
====
