name: Build

on:
  workflow_dispatch:
  
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      env: 
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: sykq
      with:
#        arguments: publish
        arguments: publishGprPublicationToGitHubPackagesRepository
        gradle-version: 7.1.1
#    - uses: actions/upload-artifact@v2
#      with:
#       name: build-artifact
#       path: | 
#         **/build/libs/*-javadoc.jar
#         **/build/libs/*-sources.jar
#         **/build/libs/*.jar
